### ISSUE TITLE
DMR ID update trouble

### ISSUE THREAD

**Issue by RecepAGulec** [ea3ihi/DMRStation-release#2]
After upgrade to v0.9 dmr id update does not work.
When I want to update DMR ids get following error message:
--------------------------------------------------
pi@raspberrypi:/opt/DMRStation $ sudo ./DMRIDUpdate.sh
ls: cannot access './DMRIds.dat.*': No such file or directory
parse error: Invalid numeric literal at line 1, column 10
--------------------------------------------------

**Comment by ea3ihi** [comment]
Have you updated the DMRIDUpdate.sh script? There is a new url to download the database, the new url is:

https://database.radioid.net/api/dmr/user/?id=%

You can check the url in the last lines of the scripts

**Comment by RecepAGulec** [comment]
Solved. That was my fault.

**Comment by ea3ihi** [comment]
Ok, thanks for confirming

**Comment by MM6NRK** [comment]
I get this when i run it with you new url .

pi@raspberrypi:~ $ cd /opt
pi@raspberrypi:/opt $ cd DMRStation
pi@raspberrypi:/opt/DMRStation $ sudo ./DMRIDUpdate.sh
./DMRIDUpdate.sh: line 95: unexpected EOF while looking for matching `''
./DMRIDUpdate.sh: line 98: syntax error: unexpected end of file

**Comment by MM6NRK** [comment]
# Generate new file
curl -s -N "https://database.radioid.net/api/dmr/user/?id=% | jq -r '.results[] | [.id, .callsign, .fname] | @csv' | sed -e 's/"//g' | sed -e 's/,/ /g' > ${DMRIDFILE}

**Comment by MM6NRK** [comment]
ok got it sorted all is good now .
