### ISSUE TITLE
version 0.9 - 2020/05/31 No shut down button .

### ISSUE THREAD

**Issue by MM6NRK** [ea3ihi/DMRStation-release#3]
Hi david from the new updates everything works fine as it should but now there is no red close down button in the INFO tab .

Thanks MM6NRK

**Comment by ea3ihi** [comment]
What ui resolution are you using? The info label now has more content and the close button probably has been pushed down out of the screen

**Comment by MM6NRK** [comment]
i have it set at this and every other tab is fine other than the info tab .

[ui]
#1=2
smallUI=2

**Comment by MM6NRK** [comment]
This is the lcd i have .
[https://www.ebay.co.uk/itm/3-5-TFT-Touch-Screen-Module-LCD-Display-Monitor-Case-for-Raspberry-Pi-A-2B-3B/303523340939?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649](url)


Resolution: | 320x480 | 

Screen size: | 3.5 inch

**Comment by ea3ihi** [comment]
If you are using a 480x320 display you can use smallUI=1

**Comment by MM6NRK** [comment]
I have used smallUI=1 and it still does not show .
Every other tab is fine .
Its no big deal as i can close it down from the DMR tab .

**Comment by ea3ihi** [comment]
Please add (or send me) a screen shot.

**Comment by MM6NRK** [comment]
Here you go .
https://ibb.co/Z8Qhfng

https://ibb.co/whCyTH8

**Comment by Jumbotroll** [comment]
I had to edit DMRStation.glade to:
800x400
On my 7" Touch screen with resolution 800x480 then the DMRstation window fit better because the tool line on the top.

Screenshot:
http://www.jadahl.com/DMRstation.png

**Comment by MM6NRK** [comment]
Ok thanks all sorted now .
