### ISSUE TITLE
Source of c2server

### ISSUE THREAD

**Issue by crazybyte** [ea3ihi/DMRStation-release#4]
Hello,

sorry for using this issue as a way to contact you (couldn't find other way). May I ask you, if is possible, please, to provide the source (the repository where to find it) for c2server, like you did for md380-tools, so that it can be compiled from scratch. Thank you and thank you DMRStation

**Comment by ea3ihi** [comment]
No problem, here you can find my fork of the codec2 repository, and there is the source for the c2server.

https://github.com/ea3ihi/codec2

**Comment by crazybyte** [comment]
Thank you
